### ISSUE TITLE
Allow Suggestions / Predictions in the Title

### ISSUE THREAD

**Issue by spslater** [msasikanth/pinnit#120]
When editing a pin suggestions aren't appearing when typing the title but they are appearing in the Description. Being able to select the suggestions (and swipe on supported keyboards) is extremely helpful and useful.

<img src="https://github.com/msasikanth/pinnit/assets/1340818/0906d57d-af64-430c-99a5-b8bff48ba563" height="500">

<img src="https://github.com/msasikanth/pinnit/assets/1340818/89629e22-84e5-43af-bda1-73173a4c16eb" height="500">

**Comment by ch3thanhs** [comment]
I get suggestions on the title on my device, try changing the keyboard.

**Comment by spslater** [comment]
Ah yes, switching to the default Google keyboard works. Thank you.
