### ISSUE TITLE
Show Chinese OEM specific warning about app killing when removed from recent/overview screen

### ISSUE THREAD

**Issue by msasikanth** [msasikanth/pinnit#21]
Show a warning dialog or view for the Chinese OEMs, since apps are killed when removed from recent/overview screen. Navigate the user to [DontKillMyApp](https://dontkillmyapp.com/) to get information on how to "fix" this.

**Comment by jahirfiquitiva** [comment]
Not sure if you've seen [Doki](https://github.com/doubledotlabs/doki), but it might help

**Comment by msasikanth** [comment]
> Not sure if you've seen [Doki](https://github.com/doubledotlabs/doki), but it might help

Yes I did, it's just I am trying to avoid using `Internet` permission for this app
