### ISSUE TITLE
Missing option "save only"

### ISSUE THREAD

**Issue by spectkiller** [msasikanth/pinnit#26]
Whenever i have to create a note in the app, i need to choose the option "save and pin" but i don't always need to pin something, i just wanna put it there.

It would be nice if there is two options, namely the original one "save and pin" and only "save". 

but currently to achieve that, i have to manually unpin it again 

i get it that its not a "note taking" app and might be against the app orginal motive but please le me know if it's possible :)

**Comment by msasikanth** [comment]
Yes, we are considering that option. It should be available in future update

**Comment by spectkiller** [comment]
thanks

**Comment by msasikanth** [comment]
This has been implemented via schedule notification. You can now add a schedule for pinning the notification in the feature and just save the note. At this point, we are not planning on adding just save only option since that defeats the purpose of the app.
