### ISSUE TITLE
Unexpected schedule behavior

### ISSUE THREAD

**Issue by Nabokov86** [msasikanth/pinnit#42]
I'm not sure if this is a bug or a feature, but if I tap "Unpin" in notifications, the notification no longer appears despite the schedule.

What I want: the notification appeared every day and I could swipe it away/unpin and it reappeared tomorrow according to the schedule.

Maybe I missed something, but the schedule seems to be working in a strange way.

**Comment by Nabokov86** [comment]
Maybe the "Repeat every..." checkbox doesn't work correctly.

**Comment by msasikanth** [comment]
Thanks for reporting the issue. That is definitely weird behaviour, can you post your device info as well, please?

**Comment by Nabokov86** [comment]
Sorry for not reporting this in the previous post. I tested it on a Nexus 5 running on Android 7. It doesn't look like a specific device problem, because I also have the same problem on android 9 on another device.

App version: 1.2.0
Android version: 7 and 9 AOSP

Battery optimization is disabled for the app, other notifications from the app work correctly.

**Comment by msasikanth** [comment]
This seems to be because the app is using a work manager instead of an alarm manager for scheduling notifications. There is another issue for tracking using alarm manager #76
