### ISSUE TITLE
QsPopupActivity visible in recents

### ISSUE THREAD

**Issue by swapnilkadlag** [msasikanth/pinnit#46]
Upon opening the app from QsPopupActivity -> Open App, the QsPopupActivity is still visible in the recents, which I'm not sure if it is the intended behaviour or not.

**Comment by swapnilkadlag** [comment]
If it is not the intended behaviour, please take a look at #47 which fixes it

**Comment by msasikanth** [comment]
This is the intended behaviour of the app, closing the issue.
