### ISSUE TITLE
Strings.xml of Spanish translation

### ISSUE THREAD

**Issue by cyanwolfg** [msasikanth/pinnit#64]
Hi, I made a Spanish translation, I share if it can be used in this cool app.
[strings-es.zip](https://github.com/msasikanth/pinnit/files/9621961/strings-es.zip)

**Comment by msasikanth** [comment]
Hello, thanks for the contribution. Can you post the transitions here as a code block or submit a PR, instead of zip file, please?

**Comment by cyanwolfg** [comment]
I do a pull request please tell me if something is bad.

**Comment by msasikanth** [comment]
Everything looks good, thanks for the contribution 😄
