### ISSUE TITLE
Android 13 - Pinnit not showing any notications

### ISSUE THREAD

**Issue by Joren1204** [msasikanth/pinnit#67]
Since updating my Pixel 6 to Android 13, Pinnit isn't showing any notifications.
In the app settings, in the "notifications" menu, there's a message telling me that

> At you request, Android is blocking this app's notifications from appearing on this device.

However, I have no idea how I could have requested that. 🤷
_Do not disturb_ is disabled, _focus mode_ isn't enabled, ...
The toggle to enable notifications is greyed out and I can't click it.

I've cleared the app storage, removed and reinstalled the app, but without any luck.

Does anyone has any idea what could be the cause of this?

(I do realise this might be not app related, but an Android issue, but didn't know where else to ask.)

Device: Google Pixel 6
OS: Android 13
App version: 1.2.3

![Screenshot (26 Sept 2022 19_12_50)](https://user-images.githubusercontent.com/17317396/192340418-5e783fd2-b0a6-49dd-a047-a883ac4f7fd0.png)

**Comment by msasikanth** [comment]
Hi, thanks for reporting the issue. Already tracking the issue [here](https://github.com/msasikanth/pinnit/issues/66) and will raise a fix for it hopefully by end of this week.
