### ISSUE TITLE
[Feature Request] 24-hour time input when scheduling a note

### ISSUE THREAD

**Issue by urmomsangus** [msasikanth/pinnit#70]
Hi, I have my Android time setup for 24-hour time. When I schedule a pinned note, the app only gives me the option for AM/PM

I would like to request either an option in the app to toggle 24 hour time, or for the app to somehow respect the Android time settings.

Thanks for the wonderful app.

**Comment by msasikanth** [comment]
That's an oversight. Thanks for raising an issue.
