### ISSUE TITLE
GitHub APK releases?

### ISSUE THREAD

**Issue by D3SOX** [msasikanth/pinnit#72]
Your app is listed on https://apt.izzysoft.de/fdroid/index/apk/dev.sasikanth.pinnit as it's not in the official F-Droid repo and I previously had APKs from there.
As far as I know, this repo is using a script to get the APK from GitHub.
I noticed you stopped attaching APKs to the releases from 1.2.5 and therefore I don't receive any updates.

Can you provide APKs again or maybe publish your app to F-Droid?

**Comment by msasikanth** [comment]
It should be available now. Please check

**Comment by D3SOX** [comment]
Thank you!

**Comment by D3SOX** [comment]
Hm, I only get "There was a problem parsing the package." when trying to install them (Android 12)

**Comment by msasikanth** [comment]
Fixed it. You should be able to download proper APKs now

**Comment by IzzySoft** [comment]
The last release is missing its APK, could you please attach it, @msasikanth? Thanks in advance!
