### ISSUE TITLE
[Feature Request] Customizable default schedule/repeat state

### ISSUE THREAD

**Issue by D3SOX** [msasikanth/pinnit#75]
I mainly use the app to schedule a one time notification so I always need to add a schedule and uncheck repeat when creating a new entry.

It would be nice if there was a setting to change the default schedule and repeat state.

**Comment by D3SOX** [comment]
No comment? Would you accept a PR for this?

**Comment by msasikanth** [comment]
Currently, I am not considering providing a setting to change the behaviour, but I might end up changing the default behaviour to not have a repeat by default.

I do have to make more changes to the app around scheduling and permission changes to better support latest version of Android. So, it will be either available as a update or as a new app depending on how much work there will be.

**Comment by msasikanth** [comment]
In the meantime, you can build the app locally and set [this](https://github.com/msasikanth/pinnit/blob/7feb61c3513145a5c554a094c6a5ce950d602867/app/src/main/java/dev/sasikanth/pinnit/data/Schedule.kt#L48) value to `null` to disable the default repeat behaviour.

**Comment by D3SOX** [comment]
Thank you for the insights and the tip that's helpful for now!
